apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocoder-api-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: geocoder-api
  template:
    metadata:
      labels:
        app: geocoder-api
    spec:
      containers:
      - image: ghcr.io/openearthplatforminitiative/geocoder-api:0.0.1
        name: geocoder-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: geocoder-api-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: geocoder-api
